config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index] do
    resources :comments, only: [:new, :show]
  end
  resources :comments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :user_id, :post_id, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"

  belongs_to :post

  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: "Comment"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :subs, presence: { message: "Must have at least one sub"}

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments

  def comments_by_parent_id
    comments_by_parent = Hash.new { |hash, key| hash[key] = [] }

    self.comments.includes(:author).each do |comment|
      comments_by_parent[comment.parent_comment_id] << comment
    end

    comments_by_parent
  end
end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post, :sub, presence: true

  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'User'

  has_many :post_subs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :post_subs
end

app/models/user.rb
class User < ApplicationRecord

  attr_reader :password

  before_validation :ensure_session_token
  validates :username, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  has_many :subs,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: 'Sub'

  has_many :posts,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "Post"

  has_many :comments,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.ensure_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def require_sign_in
    redirect_to new_session_url unless signed_in?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_url(@comment.post_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_sign_in
  before_action :require_author, only: [:edit, :update]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "Post successfully created!"
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post successfully edited!"
      redirect_to subs_url
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end

  def require_author
    @post = Post.find(params[:id])
    redirect_to sub_url(@post.sub_ids) unless current_user.id == @post.user_id
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username and/or password."]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to subs_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_sign_in, except: [:index, :show]
  before_action :require_mod, only: [:edit, :update, :destroy]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id
    if @sub.save
      flash[:notice] = "Sub successfully created!"
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      flash[:notice] = "Sub successfully edited!"
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  def require_mod
    @sub = Sub.find(params[:id])
    redirect_to subs_url unless @current_user.id == @sub.user_id
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render:new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= comment.content %> <font color="orange">- <%= comment.author.username %>
  <%= comment.created_at.strftime("%b %d %Y %H:%M") %></font>
   <%= link_to "Reply", post_comment_url(comment.post_id, comment)%>


  <ul>
    <% @comments_by_parent_id[comment.id].each do |child_comment| %>
        <li><%= render("comments/comment", comment: child_comment) %></li>
    <% end %>
  </ul>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">

  <label><b>Content</b><br>
    <textarea name="comment[content]" rows="8" cols="80"></textarea></label><br><br>

  <input type="submit" value="Create Comment">

</form>

app/views/comments/show.html.erb
<h2>Comments</h2>

<b>Comment:</b><br>
<%= @comment.content %> - <font color="orange"><%= @comment.author.username %>
  <%= @comment.created_at.strftime("%b %d %Y %H:%M") %></font><br><br>

<form action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.id %>">
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">

  <label><b>Content</b><br>
    <textarea name="comment[content]" rows="8" cols="80"></textarea></label><br><br>

  <input type="submit" value="Reply to Comment">
</form>
<%= button_to "Delete Comment", comment_url(@comment), method: :delete if current_user.id == @comment.user_id %>

<br><br><br>
<%= link_to "Back to Post", post_url(params[:post_id]) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

  </head>
  <% unless signed_in? %>
    <%= link_to "Sign In", new_session_url, method: :get %>
  <% end %>

  <% if current_user %>
    Hello, <%= current_user.username %><br>
    <%= button_to "Sign Out", session_url, method: :delete %>
  <% end %>

  <center><img src="https://www.mlssoccer.com/sites/all/themes/custom/mp7/images/share_reddit.png" alt="logo"></center>

  <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
      <%= error %><br>
    <% end %>
  <% end %>

  <%= flash[:notice] if flash[:notice] %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit a Post!</h2>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
  <input type="text" name="post[title]" value="<%= @post.title %>"></label><br><br>

  <label>URL (optional)
  <input type="text" name="post[url]" value="<%= @post.url %>"></label><br><br>

  <label>Subs
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label><% end %>
  </label><br><br>

  <label>Content (optional)<br>
    <textarea name="post[content]" rows="8" cols="80"><%= @post.content %></textarea></label><br><br>


  <input type="submit" value="Edit Post">
</form>

app/views/posts/new.html.erb
<h2>Create a Post!</h2>

<form action="/posts" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label><b>Title</b>
  <input type="text" name="post[title]"></label><br><br>

  <label><b>URL (optional)</b>
  <input type="text" name="post[url]"></label><br><br>

  <label><b>Subs</b>
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label><% end %>
  </label><br><br>

  <label><b>Content (optional)</b><br>
    <textarea name="post[content]" rows="8" cols="80"></textarea></label><br><br>

  <input type="submit" value="Create Post">
</form>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<b>Author:</b> <%= @post.author.username %><br><br>

<b>URL:</b> <a href="<%= @post.url %>"><%=@post.url %></a>


<p><b>Content:</b> <%= @post.content %></p><br><br>

<ul><b>Comments:</b>
  <% @post.comments.where(parent_comment_id: nil).each do |comment| %>
    <li><%= render("comments/comment", comment: comment) %></li>
  <% end %>
    <li></li>
    <li><%= link_to "New Comment", new_post_comment_url(@post) %></li>
</ul>

<% if @post.user_id == current_user.id %>
  <%= link_to "Edit Post", edit_post_url(@post) %><br>
  <%= button_to "Delete Post", post_url(@post), method: :delete %><br>
<% end %>
<%= link_to "Back to Sub", subs_url %>

app/views/subs/edit.html.erb
<h2>Edit a Sub!</h2>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
  <input type="text" name="sub[title]" value="<%= @sub.title %>"></label><br>
  <label>Description
  <input type="text" name="sub[description]" value="<%= @sub.description %>"></label><br>

  <input type="submit" value="Edit Sub">
</form>

app/views/subs/index.html.erb
<h2>All the Subs:</h2>

<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
  <% end %>
</ul>

<%= link_to "Create a Sub!", new_sub_url, method: :get %>

app/views/subs/new.html.erb
<h2>Create a Sub!</h2>

<form action="/subs" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
  <input type="text" name="sub[title]"></label><br><br>
  <label>Description
  <input type="text" name="sub[description]"></label><br><br>

  <input type="submit" value="Create Sub">
</form>

app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>
<p>Moderator: <%= @sub.moderator.username %></p>
<p><b>Description:</b> <%= @sub.description %></p>

<br>

<h3>Posts:</h3>
<ul>
  <% @sub.posts.each do |post| %>
    <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
  <% end %>
</ul>
<%= link_to "New Post!", new_post_url %><br><br><br>



<% if current_user && (current_user.id == @sub.user_id) %>
  <%= link_to "Edit Sub", edit_sub_url(@sub) %>
  <%= button_to "Destroy Sub", sub_url(@sub), method: :delete %>
<% end %>
<%= link_to "Back to All Subs", subs_url %>

app/views/users/new.html.erb
<h2>Sign Up!</h2>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
  <input type="text" name="user[username]"></label>
  <label>Password
  <input type="password" name="user[password]"></label>

  <input type="submit" value="Create User">
</form>